version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - battery_simulator_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mongodb_simulation_results:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - battery_simulator_network
    volumes:
      - mongodb_data_simulation_results:/data/db
    environment:
      - MONGO_INITDB_DATABASE=simulationResultsDB

  mongodb_simulationManager:
    container_name: mongodb_simulationManager
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - battery_simulator_network
    volumes:
      - mongodb_data_simulation_manager:/data/db
    environment:
      - MONGO_INITDB_DATABASE=simulationManagerDB

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - battery_simulator_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  battery_simulator:
    container_name: batterySimulationAPI
    image: batterysimulator:latest
    ports:
      - "8084:8084"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - battery_simulator_network

  celery:
    container_name: celeryWorker
    image: batterysimulator:latest
    command: ["celery", "-A", "App.API.tasks:celery", "worker", "--loglevel=info"]
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - battery_simulator
      - rabbitmq
    networks:
      - battery_simulator_network

  simulation_manager:
    container_name: simulationManager
    image: simulation_manager:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb_simulationManager:27017/simulationManagerDB
      - producer.enabled=true
    networks:
      - battery_simulator_network
    depends_on:
      - rabbitmq
      - mongodb_simulationManager
      - postgres

  user_creation_battery_simulator:
    image: user_creation_battery_simulator:latest
    container_name: user_creation
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - battery_simulator_network
    depends_on:
      - postgres
      - rabbitmq

  simulation_results:
    container_name: simulationNotificationService
    image: simulation_notification_service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb_simulation_results:27017/simulationResultsDB
    networks:
      - battery_simulator_network
    depends_on:
      - rabbitmq
      - mongodb_simulation_results

volumes:
  mongodb_data_simulation_manager:
  mongodb_data_simulation_results:
  postgres_data:

networks:
  battery_simulator_network:
    driver: bridge
    name: battery_simulator_network